#!/bin/sh
INSTALLDIR/usr/sbin/binkd -p -P 2:5020/828 INSTALLDIR/usr/etc/binkd.cfg ; sync
INSTALLDIR/usr/bin/hpt -c INSTALLDIR/usr/etc/fido/config toss ; sync
INSTALLDIR/usr/bin/hpt -c INSTALLDIR/usr/etc/fido/config link ; sync


