#!/bin/sh
#   This file is part of fidoip. It is free software and it is covered
#   by the GNU general public license. See the file LICENSE for details. */
#   Shows list of commands

if [ -e INSTALLDIR/fido/fidohelp.hlp ] ; then
cat INSTALLDIR/fido/fidohelp.hlp
else
echo
fi
